apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omeroworker
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: omeroworker
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 2Gi
