apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - svc.yaml
  - config/ice-config.yaml

configMapGenerator:
  - name: omeroserver-env
    envs:
      - config/omero-server.env
  - name: omeroserver-init
    files:
      - init.sh=config/init.sh

generatorOptions:
  disableNameSuffixHash: false
  labels:
    app: omeroserver
