apiVersion: v1
kind: Service
metadata:
  name: omeroserver
spec:
  type: ClusterIP
  selector: { app: omeroserver }
  ports:
    - { name: registry,           port: 4061, targetPort: 4061, protocol: TCP }
    - { name: registry-internal,  port: 4062, targetPort: 4062, protocol: TCP }
    - { name: glacier2,           port: 4063, targetPort: 4063, protocol: TCP }
    - { name: blitz,              port: 4064, targetPort: 4064, protocol: TCP }
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
