apiVersion: apps/v1
kind: Deployment
metadata:
  name: omeroweb
spec:
  template:
    spec:
      containers:
        - name: omeroweb
          startupProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: omeroweb-env
data:
  CONFIG_omero_web_csrf__trusted__origins: '["http://localhost"]'
