apiVersion: apps/v1
kind: Deployment
metadata:
  name: omeroserver
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: omeroserver
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
