apiVersion: apps/v1
kind: Deployment
metadata:
  name: omerothumbnail
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: omerothumbnail
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
