apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omero
spec:
  storageClassName: "cinder-nova-xfs" # change to your storage class
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  storageClassName: "cinder-nova" # change to your storage class
  resources:
    requests:
      storage: 2Gi
