apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - svc.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: database
      app.kubernetes.io/part-of: omero
